### PR TITLE
Added Fred Farwenel to the list of contributors

### PR DESCRIPTION
**Pull request by nonSerp**

### CODE REVIEW

**Review by bradmccoydev — CHANGES_REQUESTED** [review]
Please just add your name

**Review by bradmccoydev — CHANGES_REQUESTED** [review]
Please just add your name

**Comment by nonSerp** [comment]
> Please just add your name

```
| [Fred Farwenel](https://https://github.com/nonSerp) | GMT | UTC +0 | GitOps, GoLang |

**Comment by verma-kunal** [comment]
Hey @nonSerp , i would suggest you to create a fresh PR (following the instructions mentioned [here](https://github.com/bradmccoydev/mentoring/blob/main/CONTRIBUTING.md))
While making the new PR, pls do note that you only have to add your information to the "end of the document", i.e. after the information of the last contributor!
Would be closing this PR, once you have you made a new one. Do ask any doubts you would have!

Hope that make things more clear 🙂

**Pull request closed without merging**
